### ISSUE TITLE
discard file types option

### ISSUE THREAD

**Issue by TrySound** [ben-eb/postcss-discard-font-face#1]
For remove unmatched sources
```
{
  types: ['ttf', 'woff', 'svg']
}
```

**Comment by ben-eb** [comment]
Nice idea. :+1:

**Comment by TrySound** [comment]
@ben-eb Give me access. Will make PR

**Comment by ben-eb** [comment]
@TrySound Done. :smile:

**Comment by ben-eb** [comment]
@TrySound I am thinking that instead of deprecating this module, I will make this its primary feature and then delegate the 'unused' behaviour into a new module. But I think I should not bundle it with cssnano as it would then be a lossy optimisation.

**Comment by TrySound** [comment]
@ben-eb  Nice idea!

**Comment by TrySound** [comment]
@ben-eb So, can I remove your functionality?

**Comment by ben-eb** [comment]
Yep :smile:

**Comment by TrySound** [comment]
Hi, @ben-eb 
I suggest this
```js
discard(['ttf', 'woff']); // filter by extension
```

```js
discard(function (url, format) {
  // return undefined; // pass
  // return false; // remove
  // return true; // pass
  // return "newUrl"; // replace url and pass
});
```

**Comment by ben-eb** [comment]
What use case does the function fulfil? I'm not against adding it, but is it necessary? Array looks good to me.

**Comment by TrySound** [comment]
@ben-eb Maybe somebody want to filter by another url part or format.

**Comment by TrySound** [comment]
Extensions is just a sugar

**Comment by TrySound** [comment]
Also it will let to change the url

**Comment by ben-eb** [comment]
OK. Let's do that. :+1:

**Comment by TrySound** [comment]
@ben-eb Done!
