### ISSUE TITLE
Update dependencies please

### ISSUE THREAD

**Issue by deser** [ben-eb/postcss-discard-font-face#7]
Due to this module I see next warnings when building:
 37% 55/118 build modulesContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
 69% 1468/1470 build modulesContainer#eachDecl is deprecated. Use Container#walkDecls instead.
Node#removeSelf is deprecated. Use Node#remove.

**Comment by ben-eb** [comment]
PR welcome. :+1:

**Comment by deser** [comment]
Thanks!

**Comment by ben-eb** [comment]
Released in `3.0.0`.

**Comment by deser** [comment]
Sorry for not being able to help
